# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LightroomUI.ui'
#
# Created: Wed Aug 12 16:27:43 2009
#      by: PyQt4 UI code generator 4.5-snapshot-20090412
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_LightroomImport(object):
    def setupUi(self, LightroomImport):
        LightroomImport.setObjectName("LightroomImport")
        LightroomImport.resize(698, 832)
        self.centralwidget = QtGui.QWidget(LightroomImport)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mLightroomDBPath = QtGui.QLineEdit(self.groupBox)
        self.mLightroomDBPath.setObjectName("mLightroomDBPath")
        self.horizontalLayout_3.addWidget(self.mLightroomDBPath)
        self.mLightroomDBPathChoose = QtGui.QPushButton(self.groupBox)
        self.mLightroomDBPathChoose.setObjectName("mLightroomDBPathChoose")
        self.horizontalLayout_3.addWidget(self.mLightroomDBPathChoose)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox1 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mEmptyData = QtGui.QCheckBox(self.groupBox1)
        self.mEmptyData.setObjectName("mEmptyData")
        self.verticalLayout_3.addWidget(self.mEmptyData)
        self.mResetExcluded = QtGui.QCheckBox(self.groupBox1)
        self.mResetExcluded.setObjectName("mResetExcluded")
        self.verticalLayout_3.addWidget(self.mResetExcluded)
        self.line = QtGui.QFrame(self.groupBox1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.mImportKeywords = QtGui.QCheckBox(self.groupBox1)
        self.mImportKeywords.setChecked(True)
        self.mImportKeywords.setObjectName("mImportKeywords")
        self.verticalLayout_3.addWidget(self.mImportKeywords)
        self.mImportCollections = QtGui.QCheckBox(self.groupBox1)
        self.mImportCollections.setChecked(True)
        self.mImportCollections.setObjectName("mImportCollections")
        self.verticalLayout_3.addWidget(self.mImportCollections)
        self.line_2 = QtGui.QFrame(self.groupBox1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.mDryRun = QtGui.QCheckBox(self.groupBox1)
        self.mDryRun.setChecked(True)
        self.mDryRun.setObjectName("mDryRun")
        self.verticalLayout_3.addWidget(self.mDryRun)
        self.verticalLayout.addWidget(self.groupBox1)
        self.log = QtGui.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        self.log.setFont(font)
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.verticalLayout.addWidget(self.log)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.mCancelBtn = QtGui.QPushButton(self.widget)
        self.mCancelBtn.setObjectName("mCancelBtn")
        self.horizontalLayout_4.addWidget(self.mCancelBtn)
        self.mOkBtn = QtGui.QPushButton(self.widget)
        self.mOkBtn.setDefault(True)
        self.mOkBtn.setObjectName("mOkBtn")
        self.horizontalLayout_4.addWidget(self.mOkBtn)
        self.verticalLayout.addWidget(self.widget)
        LightroomImport.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(LightroomImport)
        self.statusBar.setObjectName("statusBar")
        LightroomImport.setStatusBar(self.statusBar)

        self.retranslateUi(LightroomImport)
        QtCore.QMetaObject.connectSlotsByName(LightroomImport)

    def retranslateUi(self, LightroomImport):
        LightroomImport.setWindowTitle(QtGui.QApplication.translate("LightroomImport", "Lightroom Import", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("LightroomImport", "Lightroom Catalogue Path", None, QtGui.QApplication.UnicodeUTF8))
        self.mLightroomDBPathChoose.setText(QtGui.QApplication.translate("LightroomImport", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox1.setTitle(QtGui.QApplication.translate("LightroomImport", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.mEmptyData.setToolTip(QtGui.QApplication.translate("LightroomImport", "I really hope you know what you\'re doing!!", None, QtGui.QApplication.UnicodeUTF8))
        self.mEmptyData.setText(QtGui.QApplication.translate("LightroomImport", "EMPTY TABLES - WARNING: WILL DELETE *ALL* DATA", None, QtGui.QApplication.UnicodeUTF8))
        self.mResetExcluded.setToolTip(QtGui.QApplication.translate("LightroomImport", "Enabling this option will set ALL images to \"excluded\" except the ones imported now", None, QtGui.QApplication.UnicodeUTF8))
        self.mResetExcluded.setText(QtGui.QApplication.translate("LightroomImport", "Reset \"Excluded\" Status", None, QtGui.QApplication.UnicodeUTF8))
        self.mImportKeywords.setText(QtGui.QApplication.translate("LightroomImport", "Import Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.mImportCollections.setText(QtGui.QApplication.translate("LightroomImport", "Import Collections", None, QtGui.QApplication.UnicodeUTF8))
        self.mDryRun.setToolTip(QtGui.QApplication.translate("LightroomImport", "Don\'t actually insert data, just pretend to", None, QtGui.QApplication.UnicodeUTF8))
        self.mDryRun.setText(QtGui.QApplication.translate("LightroomImport", "DryRun", None, QtGui.QApplication.UnicodeUTF8))
        self.mCancelBtn.setText(QtGui.QApplication.translate("LightroomImport", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.mOkBtn.setText(QtGui.QApplication.translate("LightroomImport", "OK", None, QtGui.QApplication.UnicodeUTF8))

